# Generated by Django 5.1.2 on 2024-10-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0005_dataset_is_active_alter_plant_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to="media/classifier/"),
        ),
    ]
