# Generated by Django 5.1.2 on 2024-10-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0007_requesthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesthistory",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="classifier.plant"
            ),
        ),
    ]
