# Generated by Django 5.1.2 on 2024-10-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0009_rename_promo_plantimage_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesthistory",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
