# Generated by Django 5.1.2 on 2024-10-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "classifier",
            "0012_dataset_unrecognized_info_alter_requesthistory_info_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesthistory",
            name="label",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="classifier.label",
            ),
        ),
    ]
