# Generated by Django 5.1.2 on 2024-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0013_alter_requesthistory_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
